import dbData from '../../accounting/mockdata/db.json';

// ─── UTILITIES ──────────────────────────────────────────────────────────────

const formatDisplayCode = (id, prefix = 'ORD') => {
  if (!id) return 'N/A';
  if (isNaN(id)) return id;
  return `${prefix}-${id.toString().padStart(3, '0')}`;
};

// ─── LOCAL STORAGE HELPERS (SHARED WITH ACCOUNTING) ────────────────────────

const getLocalInvoices = () => {
  try {
    const raw = localStorage.getItem('added_invoices');
    return raw ? JSON.parse(raw) : [];
  } catch (e) { return []; }
};

const getLocalOrders = () => {
  try {
    const raw = localStorage.getItem('added_orders');
    return raw ? JSON.parse(raw) : [];
  } catch (e) { return []; }
};

const getLocalCustomers = () => {
  try {
    const raw = localStorage.getItem('added_customers');
    return raw ? JSON.parse(raw) : [];
  } catch (e) { return []; }
};

const getInvoiceOverrides = () => {
  try {
    const raw = localStorage.getItem('invoice_overrides');
    return raw ? JSON.parse(raw) : [];
  } catch (e) { return []; }
};

const getAllCurrentInvoices = () => {
  const local = getLocalInvoices();
  const api = dbData.invoices || [];
  const overrides = getInvoiceOverrides();
  
  // Lọc bỏ các invoice trong api đã bị override
  const overrideIds = new Set(overrides.map(ov => ov.invoiceID));
  return [
    ...local,
    ...overrides,
    ...api.filter(a => !overrideIds.has(a.invoiceID))
  ];
};

// ─── SALES SERVICE LOGIC ───────────────────────────────────────────────────

const salesService = {
  // Lấy danh sách khách hàng (Gộp JSON + LocalStorage)
  getCustomers: async () => {
    const local = getLocalCustomers();
    const api = dbData.customers || [];
    
    // Thu thập thêm khách hàng từ hóa đơn/đơn hàng nếu có (trong trường hợp customerID là object hoặc tên)
    const invoices = getAllCurrentInvoices();
    const orders = [...getLocalOrders(), ...(dbData.orders || [])];
    
    // Map IDs to unique customers
    const customerMap = new Map();
    api.forEach(c => customerMap.set(c.customerID, c));
    local.forEach(c => customerMap.set(c.customerID, c));
    
    return Array.from(customerMap.values());
  },

  // Lấy danh sách đơn hàng (Gộp JSON + LocalStorage + Inferred from Invoices)
  getOrders: async () => {
    const localOrders = getLocalOrders();
    const apiOrders = dbData.orders || [];
    const allInvoices = getAllCurrentInvoices();
    const customers = await salesService.getCustomers();

    // Tập hợp tất cả đơn hàng
    let orders = [...localOrders, ...apiOrders];

    // Bổ sung các đơn hàng "vô hình" từ hóa đơn (nếu invoice có orderID mà chưa có trong list orders)
    allInvoices.forEach(inv => {
      if (inv.orderID && !orders.some(o => o.orderID === inv.orderID)) {
        orders.push({
          orderID: inv.orderID,
          customerID: inv.customerID,
          totalAmount: inv.totalAmount,
          orderDate: inv.invoiceDate,
          orderStatus: inv.status === 'PAID' ? 'DELIVERED' : 'PENDING',
          isAutoGenerated: true
        });
      }
    });

    return orders.map(order => {
      const customer = customers.find(c => c.customerID === order.customerID);
      const displayID = formatDisplayCode(order.orderID, 'ORD');
      
      return {
        ...order,
        displayID,
        customerName: customer ? (customer.companyName || `${customer.lastName} ${customer.firstName}`) : (order.customerName || 'Khách hàng lẻ'),
        date: order.orderDate || order.date || 'N/A'
      };
    }).sort((a, b) => new Date(b.date) - new Date(a.date));
  },

  // Lấy danh sách sản phẩm
  getProducts: async () => {
    return dbData.products || [];
  },

  // Lấy danh sách danh mục
  getCategories: async () => {
    return dbData.categories || [];
  },

  // Lấy thống kê Dashboard (Tính toán từ data thực tế)
  getDashboardStats: async () => {
    const orders = await salesService.getOrders();
    const customers = await salesService.getCustomers();
    const invoices = getAllCurrentInvoices();

    // Doanh thu tính trên tổng các hóa đơn
    const totalRevenue = invoices.reduce((sum, inv) => sum + (Number(inv.totalAmount) || 0), 0);
    
    return {
      totalRevenue: totalRevenue.toLocaleString('vi-VN') + ' VND',
      orderCount: orders.length,
      customerCount: customers.length,
      activeQuotes: 12 
    };
  },

  // Giả lập tạo khách hàng mới
  createCustomer: async (customerData) => {
    const local = getLocalCustomers();
    const newCustomer = {
      ...customerData,
      customerID: Date.now(),
      status: 'ACTIVE'
    };
    localStorage.setItem('added_customers', JSON.stringify([newCustomer, ...local]));
    return newCustomer;
  }
};

export default salesService;
